import browser_cookie3

class CookieExporter:
    def __init__(self, file_path="cookies.txt", filter_domain=None):
        """
        Initialize the CookieExporter class.
        
        Args:
            file_path (str): The path to save the exported cookies (default is 'cookies.txt').
            filter_domain (str): Optionally, filter cookies by domain (e.g., 'youtube.com').
        """
        self.file_path = file_path
        self.filter_domain = filter_domain

    def export_cookies_to_netscape(self):
        """
        Export cookies from supported browsers to a Netscape-style cookie file.
        This uses the browser_cookie3 library to automatically locate cookie files.
        """
        try:
            #! List of browser methods to call
            browser_methods = [
                browser_cookie3.chrome,
                browser_cookie3.firefox,
                browser_cookie3.edge,
                browser_cookie3.opera,
                browser_cookie3.vivaldi
            ]
            
            cookies = []
            print("Checking for browser cookies to export...")

            for method in browser_methods:
                try:
                    cookies.extend(method())
                except Exception as e:
                    print(f"Error fetching cookies from {method.__name__.split('.')[-1]}: {e}")

            #* Filter cookies by domain if specified
            if self.filter_domain:
                cookies = [cookie for cookie in cookies if self.filter_domain in cookie.domain]

            #* Remove duplicate cookies based on domain and name
            unique_cookies = {}
            for cookie in cookies:
                key = (cookie.domain, cookie.name)
                if key not in unique_cookies:
                    unique_cookies[key] = cookie

            cookies = list(unique_cookies.values())

            if cookies:
                with open(self.file_path, 'w') as f:
                    f.write("# Netscape HTTP Cookie File\n")
                    f.write("# This file is generated by browser_cookie3.\n")
                    f.write("# Format: domain\tflag\tpath\tsecure\texpiration\tname\tvalue\n\n")
                    
                    for cookie in cookies:
                        f.write(f"{cookie.domain}\t"
                                f"{'TRUE' if cookie.domain.startswith('.') else 'FALSE'}\t"
                                f"{cookie.path}\t"
                                f"{'TRUE' if cookie.secure else 'FALSE'}\t"
                                f"{int(cookie.expires) if cookie.expires else 0}\t"
                                f"{cookie.name}\t"
                                f"{cookie.value}\n")
                print(f"Cookies exported successfully to {self.file_path}")
            else:
                print("No cookies found for the specified browsers.")
        except Exception as e:
            print(f"Error exporting cookies: {e}")
